-- 코드를 입력하세요
SELECT FLAVOR
FROM (SELECT FIRST_HALF.FLAVOR, total_order + sum_total_order
      FROM FIRST_HALF, 
      (SELECT FLAVOR, SUM(TOTAL_ORDER) AS SUM_TOTAL_ORDER FROM JULY GROUP BY FLAVOR) SUM_JULY
      WHERE FIRST_HALF.FLAVOR = SUM_JULY.FLAVOR
      ORDER BY total_order + sum_total_order DESC
     )
WHERE ROWNUM <= 3
